version: '2'
services:
  web:
    build: .
    restart: always
    # command: npm run dev
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - BASE_URL=http://liberte-esthetique.fr
    volumes:
      - .:/usr/src/app/:Z
    ports:
      - "3000:3000"
